common:
  servername: commonbackground
  timeformat: yyyy-MM-dd HH:mm:ss

server:
  port: 5005

logging:
  level:
    root: info

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    #8.Xmysql需要cj中缀 以下版本不需要
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.112.172:10087/CommonBackground?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
  redis:
      host: 172.29.112.172
      port: 6379
      password: redis
      database: 0
      lettuce:
        pool:
          # 连接池中的最大空闲连接 默认8
          max-idle: 16
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 32
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: 300ms
      timeout: 30000

mybatis:
  #映射文件路径
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cb.Entity
  configuration:
    map-underscore-to-camel-case: true

# JWT配置
jwt:
  # 密匙Key
  secret: JWTSecretTest
  tokenHeader: Authorization
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 86400
  # 配置白名单（不需要认证）
  antMatchers: /login/**,/register/**,/static/**

