DROP DATABASE IF EXISTS CommonBackground;
CREATE DATABASE IF
	NOT EXISTS CommonBackground DEFAULT CHARACTER
	SET utf8 DEFAULT COLLATE utf8_general_ci;
USE CommonBackground;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`id` BIGINT ( 20 ) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`username` VARCHAR ( 64 ) NOT NULL COMMENT '用户名',
	`password` VARCHAR ( 255 ) NOT NULL COMMENT '密码',
	`email` VARCHAR ( 255 ) DEFAULT NULL COMMENT '邮箱',
	`mobile` VARCHAR ( 20 ) DEFAULT NULL COMMENT '电话',
	`nickname` VARCHAR ( 255 ) DEFAULT NULL COMMENT '显示用昵称',
	`available` TINYINT ( 1 ) NOT NULL DEFAULT 1 COMMENT '用户可用性',
	`login_ip` VARCHAR ( 255 ) DEFAULT NULL COMMENT '最后一次登陆IP',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后一次更新时间',
	PRIMARY KEY ( `id` ),
	UNIQUE KEY `user_name_unique` ( `username` ) USING BTREE,
	KEY `email` ( `email` ),
	KEY `mobile` ( `mobile` )
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT='用户表';

DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `role_name` varchar(50) NOT NULL COMMENT '角色名称',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT='角色表';

INSERT INTO roles (role_name) VALUES ('superadmin');
INSERT INTO roles (role_name) VALUES ('admin');
INSERT INTO roles (role_name) VALUES ('normal');


DROP TABLE IF EXISTS `auths`;
CREATE TABLE `auths` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` varchar(50) NOT NULL COMMENT '权限名称',
  `permission` varchar(200) DEFAULT NULL COMMENT '权限标识',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT='权限表';

DROP TABLE IF EXISTS `user_role`;
CREATE TABLE `user_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `role_id` BIGINT DEFAULT NULL COMMENT '角色ID',

  FOREIGN KEY(user_id) REFERENCES users(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY(role_id) REFERENCES roles(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT='用户角色关系表';

DROP TABLE IF EXISTS `role_auth`;
CREATE TABLE `role_auth` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `role_id` BIGINT DEFAULT NULL COMMENT '角色ID',
  `auth_id` BIGINT DEFAULT NULL COMMENT '权限ID',

  FOREIGN KEY(role_id) REFERENCES roles(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY(auth_id) REFERENCES auths(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT='角色权限关系表';

SET FOREIGN_KEY_CHECKS =1